### ISSUE TITLE
the website of anth repo needs to be optimized

### ISSUE THREAD

**Issue by emeuler** [edonyM/anth#8]
* https://github.com/spring-projects/spring-framework/tree/gh-pages
* https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/

**Comment by emeuler** [comment]
[try this github pages infrastructure](https://github.com/spring-projects/gh-pages)

**Comment by edonyzpc** [comment]
http://www.stephaniehicks.com/githubPages_tutorial/pages/githubpages-jekyll.html

**Comment by edonyzpc** [comment]
[finished](https://emanth.github.io/anth)
